data:
  path: commonlit-readability-prize/train.csv
  num_folds: 4
  fold_index: 0
  random_seed: 42
model:
  name: facebook/bart-large-mnli
  max_seq_len: 256
  num_reinit_layers: 6
  classifier_dropout: 0.000257647987869182
  random_seed: 9
optim:
  learning_rate: 5.748103051486744e-05
  layerwise_lr_decay: 0.9421652627561518
  weight_decay: 0.044751381507700964
  max_grad_norm: 0
train:
  epochs: 5
  warmup_ratio: 0.09693773485076773
  batch_size: 8
  accumulate_grads: 2
  validation_ratio: 0.25
