data:
  path: commonlit-readability-prize/train.csv
  num_folds: 4
  fold_index: 3
  random_seed: 42
model:
  name: facebook/bart-large-mnli
  max_seq_len: 256
  num_reinit_layers: 0
  classifier_dropout: 0.1599550339975712
  random_seed: 5
optim:
  learning_rate: 7.753291585960636e-05
  layerwise_lr_decay: 0.9627979533666388
  weight_decay: 0.03647710625747597
  max_grad_norm: 1.0
train:
  epochs: 5
  warmup_ratio: 0.03162274689833056
  batch_size: 8
  accumulate_grads: 2
  validation_ratio: 0.25
