data:
  path: commonlit-readability-prize/train.csv
  num_folds: 4
  fold_index: 0
  random_seed: 42
model:
  name: facebook/bart-large
  max_seq_len: 256
  num_reinit_layers: 0
  classifier_dropout: 0.28467121228435827
  random_seed: 0
optim:
  learning_rate: 3.7542069114797755e-05
  layerwise_lr_decay: 0.9851854311584891
  weight_decay: 0.06926376255442937
  max_grad_norm: 1.0
train:
  epochs: 5
  warmup_ratio: 0.026372260158273767
  batch_size: 8
  accumulate_grads: 2
  validation_ratio: 0.25
