data:
  path: commonlit-readability-prize/train.csv
  num_folds: 4
  fold_index: 2
  random_seed: 42
model:
  name: facebook/bart-large
  max_seq_len: 256
  num_reinit_layers: 2
  classifier_dropout: 0.0015117650340659159
  random_seed: 30
optim:
  learning_rate: 9.292384444141514e-05
  layerwise_lr_decay: 0.9357532051938279
  weight_decay: 0.14735229977998518
  max_grad_norm: 0
train:
  epochs: 5
  warmup_ratio: 0.1668212555239293
  batch_size: 8
  accumulate_grads: 4
  validation_ratio: 0.25
