data:
  path: commonlit-readability-prize/train.csv
  num_folds: 4
  fold_index: 0
  random_seed: 42
model:
  name: facebook/bart-base
  max_seq_len: 256
  num_reinit_layers: 4
  classifier_dropout: 0.1742787129905743
  random_seed: 9
optim:
  learning_rate: 6.243002940449189e-05
  layerwise_lr_decay: 0.8404602561275473
  weight_decay: 0.051072417129422544
  max_grad_norm: 1.0
train:
  epochs: 5
  warmup_ratio: 0.19391244766659058
  batch_size: 16
  accumulate_grads: 1
  validation_ratio: 0.25
