data:
  path: commonlit-readability-prize/train.csv
  num_folds: 4
  fold_index: 1
  random_seed: 42
model:
  name: facebook/bart-large-mnli
  max_seq_len: 256
  num_reinit_layers: 2
  classifier_dropout: 0.08407925160197625
  random_seed: 11
optim:
  learning_rate: 6.048540106522396e-05
  layerwise_lr_decay: 0.9422216960650063
  weight_decay: 0.1372754625475883
  max_grad_norm: 0
train:
  epochs: 5
  warmup_ratio: 0.053695247699849805
  batch_size: 8
  accumulate_grads: 2
  validation_ratio: 0.25
