data:
  path: commonlit-readability-prize/train.csv
  num_folds: 4
  fold_index: 3
  random_seed: 42
model:
  name: facebook/bart-large
  max_seq_len: 256
  num_reinit_layers: 3
  classifier_dropout: 0.0560191775581918
  random_seed: 14
optim:
  learning_rate: 6.618217214006115e-05
  layerwise_lr_decay: 0.9920352397221887
  weight_decay: 0.08466640481641688
  max_grad_norm: 0
train:
  epochs: 5
  warmup_ratio: 0.11802415444440627
  batch_size: 8
  accumulate_grads: 2
  validation_ratio: 0.25
