data:
  path: commonlit-readability-prize/train.csv
  num_folds: 4
  fold_index: 3
  random_seed: 42
model:
  name: facebook/bart-base
  max_seq_len: 256
  num_reinit_layers: 2
  classifier_dropout: 0.017580793260758114
  random_seed: 36
optim:
  learning_rate: 7.30629333347816e-05
  layerwise_lr_decay: 0.9336409317715905
  weight_decay: 0.11788982371036308
  max_grad_norm: 0.0
train:
  epochs: 5
  warmup_ratio: 0.0343885370258378
  batch_size: 16
  accumulate_grads: 1
  validation_ratio: 0.25
