data:
  path: commonlit-readability-prize/train.csv
  num_folds: 4
  fold_index: 3
  random_seed: 42
model:
  name: microsoft/deberta-base
  max_seq_len: 256
  num_reinit_layers: 3
  classifier_dropout: 0.00034420020793203034
  random_seed: 37
optim:
  learning_rate: 4.812069403036804e-05
  layerwise_lr_decay: 0.9386659066220938
  weight_decay: 0.05581342726087063
  max_grad_norm: 0
train:
  epochs: 5
  warmup_ratio: 0.15728947819099967
  batch_size: 16
  accumulate_grads: 1
  validation_ratio: 0.25
