data:
  path: commonlit-readability-prize/train.csv
  num_folds: 4
  fold_index: 2
  random_seed: 42
model:
  name: microsoft/deberta-large
  max_seq_len: 256
  num_reinit_layers: 1
  classifier_dropout: 0.0007103714666583452
  random_seed: 32
optim:
  learning_rate: 3.5166897900983e-05
  layerwise_lr_decay: 0.974397951338147
  weight_decay: 0.03234913115456724
  max_grad_norm: 0
train:
  epochs: 5
  warmup_ratio: 0.19214098675128952
  batch_size: 8
  accumulate_grads: 2
  validation_ratio: 0.25
