data:
  path: commonlit-readability-prize/train.csv
  num_folds: 4
  fold_index: 1
  random_seed: 42
model:
  name: microsoft/deberta-base
  max_seq_len: 256
  num_reinit_layers: 0
  classifier_dropout: 0.3876082695020734
  random_seed: 6
optim:
  learning_rate: 2.080865831679939e-05
  layerwise_lr_decay: 0.9680406539676276
  weight_decay: 0.1700764515281492
  max_grad_norm: 1.0
train:
  epochs: 5
  warmup_ratio: 0.08096557401223052
  batch_size: 16
  accumulate_grads: 1
  validation_ratio: 0.25
