data:
  path: commonlit-readability-prize/train.csv
  num_folds: 4
  fold_index: 0
  random_seed: 42
model:
  name: microsoft/deberta-large
  max_seq_len: 256
  num_reinit_layers: 8
  classifier_dropout: 0.04842503392576433
  random_seed: 33
optim:
  learning_rate: 2.071317245066907e-05
  layerwise_lr_decay: 0.9364637421222237
  weight_decay: 0.07369041203138087
  max_grad_norm: 1.0
train:
  epochs: 5
  warmup_ratio: 0.06216757112780733
  batch_size: 8
  accumulate_grads: 2
  validation_ratio: 0.25
