data:
  path: commonlit-readability-prize/train.csv
  num_folds: 4
  fold_index: 3
  random_seed: 42
model:
  name: microsoft/deberta-large
  max_seq_len: 256
  num_reinit_layers: 0
  classifier_dropout: 0.0037083514422684566
  random_seed: 7
optim:
  learning_rate: 3.8614665485658645e-05
  layerwise_lr_decay: 0.9580950588700067
  weight_decay: 0.1840915845086419
  max_grad_norm: 1.0
train:
  epochs: 5
  warmup_ratio: 0.07556785591993151
  batch_size: 8
  accumulate_grads: 2
  validation_ratio: 0.25
