data:
  path: commonlit-readability-prize/train.csv
  num_folds: 4
  fold_index: 1
  random_seed: 42
model:
  name: microsoft/deberta-large
  max_seq_len: 256
  num_reinit_layers: 8
  classifier_dropout: 0.12429101691933031
  random_seed: 0
optim:
  learning_rate: 1.7363794071967777e-05
  layerwise_lr_decay: 0.9920497175155503
  weight_decay: 0.1538447546158111
  max_grad_norm: 0
train:
  epochs: 5
  warmup_ratio: 0.0427620416537791
  batch_size: 8
  accumulate_grads: 2
  validation_ratio: 0.25
