data:
  path: commonlit-readability-prize/train.csv
  num_folds: 4
  fold_index: 0
  random_seed: 42
model:
  name: microsoft/deberta-base
  max_seq_len: 256
  num_reinit_layers: 0
  classifier_dropout: 0.18197349765318316
  random_seed: 18
optim:
  learning_rate: 6.613136682162675e-05
  layerwise_lr_decay: 0.8615728063391663
  weight_decay: 0.04715018236927879
  max_grad_norm: 1.0
train:
  epochs: 5
  warmup_ratio: 0.14345236169180875
  batch_size: 16
  accumulate_grads: 1
  validation_ratio: 0.25
