data:
  path: commonlit-readability-prize/train.csv
  num_folds: 4
  fold_index: 2
  random_seed: 42
model:
  name: distilroberta-base
  max_seq_len: 256
  num_reinit_layers: 1
  classifier_dropout: 0.18203670508702902
  random_seed: 13
optim:
  learning_rate: 7.094199845044024e-05
  layerwise_lr_decay: 0.800822231046315
  weight_decay: 0.06581008239601757
  max_grad_norm: 0
train:
  epochs: 5
  warmup_ratio: 0.01831317354783218
  batch_size: 16
  accumulate_grads: 1
  validation_ratio: 0.25
