data:
  path: commonlit-readability-prize/train.csv
  num_folds: 4
  fold_index: 0
  random_seed: 42
model:
  name: distilroberta-base
  max_seq_len: 256
  num_reinit_layers: 0
  classifier_dropout: 0.3936794583641313
  random_seed: 16
optim:
  learning_rate: 5.508589000683315e-05
  layerwise_lr_decay: 0.9457396767286376
  weight_decay: 0.1317695791286573
  max_grad_norm: 1.0
train:
  epochs: 5
  warmup_ratio: 0.10399744605535563
  batch_size: 16
  accumulate_grads: 1
  validation_ratio: 0.25
