data:
  path: commonlit-readability-prize/train.csv
  num_folds: 4
  fold_index: 3
  random_seed: 42
model:
  name: distilroberta-base
  max_seq_len: 256
  num_reinit_layers: 1
  classifier_dropout: 0.018371813567829534
  random_seed: 21
optim:
  learning_rate: 4.759129598770071e-05
  layerwise_lr_decay: 0.8718174441747438
  weight_decay: 0.18841117350401265
  max_grad_norm: 0
train:
  epochs: 5
  warmup_ratio: 0.04708174250262142
  batch_size: 16
  accumulate_grads: 1
  validation_ratio: 0.25
