data:
  path: commonlit-readability-prize/train.csv
  num_folds: 4
  fold_index: 1
  random_seed: 42
model:
  name: distilroberta-base
  max_seq_len: 256
  num_reinit_layers: 1
  classifier_dropout: 0.04004424291715747
  random_seed: 27
optim:
  learning_rate: 6.60527571103659e-05
  layerwise_lr_decay: 0.8079169557896099
  weight_decay: 0.06618158460796708
  max_grad_norm: 0
train:
  epochs: 5
  warmup_ratio: 0.006779480681570742
  batch_size: 16
  accumulate_grads: 1
  validation_ratio: 0.25
