data:
  path: commonlit-readability-prize/train.csv
  num_folds: 4
  fold_index: 2
  random_seed: 42
model:
  name: google/electra-large-discriminator
  max_seq_len: 256
  num_reinit_layers: 3
  classifier_dropout: 0.05285540782616627
  random_seed: 21
optim:
  learning_rate: 3.399384804052477e-05
  layerwise_lr_decay: 0.9745520327933389
  weight_decay: 0.0727873811352816
  max_grad_norm: 0
train:
  epochs: 5
  warmup_ratio: 0.07373960661840476
  batch_size: 16
  accumulate_grads: 1
  validation_ratio: 0.25
