data:
  path: commonlit-readability-prize/train.csv
  num_folds: 4
  fold_index: 3
  random_seed: 42
model:
  name: google/electra-large-discriminator
  max_seq_len: 256
  num_reinit_layers: 2
  classifier_dropout: 0.009016861959666604
  random_seed: 34
optim:
  learning_rate: 6.0808407745227256e-05
  layerwise_lr_decay: 0.9468366408902053
  weight_decay: 0.07487054386982327
  max_grad_norm: 1.0
train:
  epochs: 5
  warmup_ratio: 0.04954663280486704
  batch_size: 16
  accumulate_grads: 1
  validation_ratio: 0.25
