data:
  path: commonlit-readability-prize/train.csv
  num_folds: 4
  fold_index: 0
  random_seed: 42
model:
  name: google/electra-base-discriminator
  max_seq_len: 256
  num_reinit_layers: 2
  classifier_dropout: 0.2421718899587863
  random_seed: 0
optim:
  learning_rate: 9.778941435398107e-05
  layerwise_lr_decay: 0.873484147599587
  weight_decay: 0.19347070160327626
  max_grad_norm: 0
train:
  epochs: 5
  warmup_ratio: 0.13043460129944245
  batch_size: 16
  accumulate_grads: 1
  validation_ratio: 0.25
