data:
  path: commonlit-readability-prize/train.csv
  num_folds: 4
  fold_index: 2
  random_seed: 42
model:
  name: google/electra-base-discriminator
  max_seq_len: 256
  num_reinit_layers: 1
  classifier_dropout: 0.0662009663441572
  random_seed: 31
optim:
  learning_rate: 5.926456422385455e-05
  layerwise_lr_decay: 0.9469149762420512
  weight_decay: 0.005551542933081726
  max_grad_norm: 0
train:
  epochs: 5
  warmup_ratio: 0.0774093129161433
  batch_size: 16
  accumulate_grads: 1
  validation_ratio: 0.25
