data:
  path: commonlit-readability-prize/train.csv
  num_folds: 4
  fold_index: 0
  random_seed: 42
model:
  name: microsoft/mpnet-base
  max_seq_len: 256
  num_reinit_layers: 3
  classifier_dropout: 0.3888120120236391
  random_seed: 18
optim:
  learning_rate: 9.469477693420255e-05
  layerwise_lr_decay: 0.8784852624669189
  weight_decay: 0.1152613962650717
  max_grad_norm: 0.0
train:
  epochs: 5
  warmup_ratio: 0.002168924068484967
  batch_size: 16
  accumulate_grads: 1
  validation_ratio: 0.25
