data:
  path: commonlit-readability-prize/train.csv
  num_folds: 4
  fold_index: 3
  random_seed: 42
model:
  name: facebook/muppet-roberta-base
  max_seq_len: 256
  num_reinit_layers: 1
  classifier_dropout: 0.3399598557882175
  random_seed: 28
optim:
  learning_rate: 4.8392899137732896e-05
  layerwise_lr_decay: 0.9888583875871702
  weight_decay: 0.19021186632554363
  max_grad_norm: 0
train:
  epochs: 5
  warmup_ratio: 0.026695369290871462
  batch_size: 16
  accumulate_grads: 1
  validation_ratio: 0.25
