data:
  path: commonlit-readability-prize/train.csv
  num_folds: 4
  fold_index: 0
  random_seed: 42
model:
  name: facebook/muppet-roberta-base
  max_seq_len: 256
  num_reinit_layers: 0
  classifier_dropout: 0.06521231452983044
  random_seed: 15
optim:
  learning_rate: 6.879067319909872e-05
  layerwise_lr_decay: 0.9502522748882906
  weight_decay: 0.07639466025331808
  max_grad_norm: 1.0
train:
  epochs: 5
  warmup_ratio: 0.1298288233256766
  batch_size: 32
  accumulate_grads: 1
  validation_ratio: 0.25
