data:
  path: commonlit-readability-prize/train.csv
  num_folds: 4
  fold_index: 1
  random_seed: 42
model:
  name: roberta-large
  max_seq_len: 256
  num_reinit_layers: 3
  classifier_dropout: 0.029782611821507272
  random_seed: 0
optim:
  learning_rate: 3.366833194942433e-05
  layerwise_lr_decay: 0.959483674214067
  weight_decay: 0.08126404362309368
  max_grad_norm: 1.0
train:
  epochs: 5
  warmup_ratio: 0.08434706214424167
  batch_size: 16
  accumulate_grads: 1
  validation_ratio: 0.25
