data:
  path: commonlit-readability-prize/train.csv
  num_folds: 4
  fold_index: 2
  random_seed: 42
model:
  name: roberta-large
  max_seq_len: 256
  num_reinit_layers: 8
  classifier_dropout: 0.011122168219813561
  random_seed: 33
optim:
  learning_rate: 4.215222472844798e-05
  layerwise_lr_decay: 0.9862749858864639
  weight_decay: 0.050754276556361104
  max_grad_norm: 0.0
train:
  epochs: 5
  warmup_ratio: 0.04594716569048647
  batch_size: 16
  accumulate_grads: 1
  validation_ratio: 0.25
