data:
  path: commonlit-readability-prize/train.csv
  num_folds: 4
  fold_index: 3
  random_seed: 42
model:
  name: roberta-base
  max_seq_len: 256
  num_reinit_layers: 4
  classifier_dropout: 0.38310290078917236
  random_seed: 9
optim:
  learning_rate: 6.354126050451375e-05
  layerwise_lr_decay: 0.8650541037422859
  weight_decay: 0.18254097558204307
  max_grad_norm: 0
train:
  epochs: 5
  warmup_ratio: 0.005647784816987616
  batch_size: 16
  accumulate_grads: 1
  validation_ratio: 0.25
