data:
  path: commonlit-readability-prize/train.csv
  num_folds: 4
  fold_index: 3
  random_seed: 42
model:
  name: roberta-large
  max_seq_len: 256
  num_reinit_layers: 0
  classifier_dropout: 0.18992949529799025
  random_seed: 25
optim:
  learning_rate: 8.928151036101666e-05
  layerwise_lr_decay: 0.9657180475722092
  weight_decay: 0.13947975926433623
  max_grad_norm: 1.0
train:
  epochs: 5
  warmup_ratio: 0.09614489866673037
  batch_size: 16
  accumulate_grads: 2
  validation_ratio: 0.25
